import causation_rating
from causation_rating.bayesian_optimization import objective, BayesianOptimization
from causation_rating.model_eval import final_model_best_param
import torch

if __name__ == "__main__":
    # You always need to set constants before using the model! For details, see the constants.py file and README.md.
    causation_rating.set_config(DEVICE = torch.device("cuda"), 
                                DATASET_PATH = 'https://huggingface.co/datasets/kelingwang/causation_strength_rating/resolve/main/rating_dr1.csv',
                                #BATCH_SIZE = 128,
                                TEST_DATA_NAME = 'test_dr1.csv', # This file is automatically generated by the split_dataset function called within BayesianOptimization
                                )

    # Run the Bayesian optimization
    best_params, final_metrics = BayesianOptimization(objective=objective, study_name='causation_rating', n_trials = 10)

    print(best_params)
    print(final_metrics)
